### ISSUE TITLE
启用报错

### ISSUE THREAD

**Issue by QuincySx** [musnow/reward-for-typecho#1]
环境：阿里云虚拟主机
描述：开启插件显示 Database Query Error
图片：
![image](https://user-images.githubusercontent.com/13297229/41579215-8c3bb412-73c8-11e8-9af4-17251c63250d.png)

![image](https://user-images.githubusercontent.com/13297229/41579202-82b8612e-73c8-11e8-8e7a-ca5c9c731653.png)

**Comment by musnow** [comment]
在`config.inc.php`，在最后一行加上，然后发一下报错信息
`define('__TYPECHO_DEBUG__', true);`

**Comment by QuincySx** [comment]
因为你的 sql 语句是 5.5 的我用的是 5.1 语法报错了
